### ISSUE TITLE
[BUG] 403 error when saving options

### ISSUE THREAD

**Issue by spiralofhope** [bmarshall511/wordpress-zero-spam#290]
I am unable to make any options changes.

**To Reproduce**

1. disable all other addons
2. visit `/wp-admin/options-general.php?page=wordpress-zero-spam-settings`
3. Click `Override & Update Settings`
4. Click `Save Settings` at the bottom
5. See error:

```
403
Forbidden
Access to this resource on the server is denied!
```

**Desktop:**
- Edge Version 96.0.1054.29 (Official build) (64-bit)
  - No addons are installed
- Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)
  - Shields has been disabled
  - Ad-blocking has been disabled

**Additional context**

I may have aggressive website protection from my host directly, because a user (even myself) can get a 403 when visiting many pages simultaneously.  I am still investigating that.

There is no similar problem with any other addon.

**Comment by bmarshall511** [comment]
@spiralofhope Hmm, that's no good. Haven't received other reports of this and am unable to replicate myself or existing or fresh WordPress site installs. What version of the Zero Spam plugin are you running?

**Comment by spiralofhope** [comment]
I'm using 5.2.7 (latest)

I checked and set permissions throughout the install (755 / 644) and that particular file should be accessible.

I wondered if there's something in my `.htaccess` which is interfering, but renaming it didn't help.  Maybe I need to restart something in my server for that to take effect?

I haven't checked into any server-side security yet.  I am not aware of anything existing.

**Comment by bmarshall511** [comment]
@spiralofhope Not sure, not able to replicate it. Are you seeing anything in the server error logs?

**Comment by spiralofhope** [comment]
I don't know what to look for in the logs.  I don't have separate error logs, but my regular logs don't show anything when I filter for "`options`".  I do see that my IP address is being logged, and I believe it other activities correctly.

I found that my hosting has something called "ModSecurity", which I learned is known to throw `403 Forbidden` errors.  Initially, disabling ModSecurity did not change this problem; I still got the error.

I did find a sort of workaround.

1. Disable all other addons
2. Disable "ModSecurity"
3. Visit `/wp-admin/options-general.php?page=wordpress-zero-spam-settings`
4. Click `Override & Update Settings`
5. Make my preferred changes.
6. Click `Save Settings` at the bottom

I can re-enable ModSecurity afterwards.

Curiously, I am unable to simply:

1. Disable "ModSecurity"
3. Visit `/wp-admin/options-general.php?page=wordpress-zero-spam-settings`
5. Make my preferred changes.
6. Click `Save Settings` at the bottom

.. I must always follow the first workaround and click `Override & Update Settings`.

**Comment by bmarshall511** [comment]
@spiralofhope Thanks for making me aware of this. This might be an issue with you're particular server/setup, but I do have an idea that may fix the issue for you.

If you don't mind, can you install the beta version of Zero Spam here: https://github.com/bmarshall511/wordpress-zero-spam/archive/refs/heads/master.zip and give that a try with ModSecurity enabled. I pushed on a fix for how that action gets processed and hoping it'll fix the issue you're running into.

**Comment by spiralofhope** [comment]
I attempted an installation of that file, and when activating it, I got this error:

```
Fatal error: Cannot redeclare zerospam_load_plugin_textdomain() (previously declared in /path/to/blog.spiralofhope.com/wp-content/plugins/zero-spam/wordpress-zero-spam.php:56) in /path/to/blog.spiralofhope.com/wp-content/plugins/wordpress-zero-spam-master/wordpress-zero-spam.php on line 55
```

(`/path/to` is to redact my info)

I did not remove the addon first, and I still had ModSecurity enabled.

**Comment by spiralofhope** [comment]
Sorry, I saw that `5.2.7` was still running.  When I disabled `5.2.7` I was able to enable what you gave me (listed as `5.2.8`)

It ran without the error.

However, when reproducing the error, I did still see it when I have ModSecurity enabled.  I just went to the settings page and clicked save, and the 403 is shown.

**Comment by bmarshall511** [comment]
@spiralofhope Gotcha, seems like an issue with your specific server/setup. I haven't been able to reproduce it or had any other people report it. The next update will include a refactor of how those actions are processed, hopefully once released, it'll resolve your problem.

Closing this for now, but will re-open if others are seeing this or are able to reproduce it.

**Comment by spiralofhope** [comment]
The official 5.2.8 resolves my problem; thanks for your effort!

**Comment by bmarshall511** [comment]
Excellent, good to hear!

**Comment by spiralofhope** [comment]
The official 5.3.5 or earlier release has reintroduced the issue.

**Comment by bmarshall511** [comment]
@spiralofhope We're unable to reproduce this. Can you provide more details (i.e. an export of your settings, version of the plugin, the steps to take to reproduce this error, etc.)?

**Comment by spiralofhope** [comment]
I've reproduced it on my end.

- Uninstall
- Reinstall
- Go to settings
- Under "Use Blocked Email Domains Recommendation" click `[Override & Update Blocked Email Domains]`
- Save settings
- An error message is seen:

```
403
Forbidden
Access to this resource on the server is denied!
```
